### ISSUE TITLE
wps_parameters config builder

### ISSUE THREAD

**Issue by sum1lim** [pacificclimate/osprey#25]
RVIC 1.1.0.post1 runs based only on config files, which degrades the user-friendliness of the software. Therefore, a config_builder program, which takes user inputs to create config files, is needed for each process.

For `RVIC parameters`, refer to the [document page](https://rvic.readthedocs.io/en/latest/user-guide/parameters/) to see what contents should be included in the config file.

**Comment by eyvorchuk** [comment]
This is a duplicate of [issue 23](https://github.com/pacificclimate/osprey/issues/23). Are you interested in doing this instead?

**Comment by sum1lim** [comment]
Oh, I did not see the issue, I will close this promptly.
