### ISSUE TITLE
Single process combining wps_parameters and wps_convolution

### ISSUE THREAD

**Issue by sum1lim** [pacificclimate/osprey#29]
Since 'RVIC convolution' is followed by 'parameters` process` most of the time except for the situations using pre-generated `parameters` output repeatedly, I think it is worth to consider creating a single process that runs both modules. Without this, users would have to follow 6 steps to run RVIC:

1. Configure `parameters` input.
2. Run `wps_parameters`
3. Download the `parameters` output.
4. Configure `Convolution` input.
5. Run `wps_convolution`.
6. Download the `convolution` output.

We could reduce it into 3 steps of `configure - run - download`. 
@corviday @nikola-rados @eyvorchuk What do you think? Is it worth to implement this additional process?

**Comment by corviday** [comment]
Seems like a good idea to me! The parametrization process is so quick compared to the convolution process I don't think we really need to worry about making it easy for people to reuse parametrizations.

**Comment by eyvorchuk** [comment]
Yeah, I thought of this for a bit before starting the project, but I wasn't sure how feasible it is. Seems like it'll work fine, though.

**Comment by sum1lim** [comment]
Cool! Thanks for the quick reply. I will work on it.
